#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# T31L MOES WCM-p52
if [ "$1" = "atbm601x-t31-moes-wcm-p52" ]; then
	#set_gpio 6 1
	modprobe atbm6012b_wifi_usb
	exit 0
fi

exit 1
