#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# RTL8188FTV on the USB bus, powered from GPIO 52 (high = on)
if [ "$1" = "rtl8188fu-hi3516ev200-imou-cue2" ]; then
	set_gpio 52 1
	modprobe 8188fu
	exit 0
fi

exit 1
