#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

if [ "$1" = "rtl8733bu-gk7201v200-xm" ]; then
	set_gpio 9 0
	modprobe 8733bu rtw_power_mgnt=0 rtw_ips_mode=0 rtw_enusbss=0
	exit 0
fi

exit 1
