#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# SSC30KQ CMCC DS YTJ5301
if [ "$1" = "rtl8188fu-ssc30kq-cmcc-ds-ytj5301" ]; then
	#set_gpio 6 1
	modprobe 8188fu
	exit 0
fi

exit 1
