#!/bin/sh

case "$1" in
	start)
		echo "Loading vendor modules..."
		vendor=$(ipcinfo -v)
		load_"$vendor" -i
		devmem 0x100c0058 32 0
		gpio set 38
		;;

	stop)
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac
