#!/bin/sh
#
# OpenIPC.org | 2024
#

PATH_MODULE=/lib/modules/4.9.84/sigmastar
PATH_SENSOR=$PATH_MODULE/sensor

detect_sensor() {
	insmod $PATH_SENSOR/sensor_config.ko
	if [ -e /dev/srcfg ]; then
		echo srcfg 0 1 0 0 0 0 > /dev/srcfg
		rmmod sensor_config
	fi
	SENSOR=$(ipcinfo -s)
}

set_sensor() {
	case $SENSOR in
		imx307|imx335|imx347|imx415)
			insmod $PATH_SENSOR/sensor_${SENSOR}_mipi.ko chmap=1
			;;
		*)
			echo -e "\n\e[1;31mUNSUPPORTED sensor - $SENSOR\e[0m\n" | logger -s -t OpenIPC
			;;
	esac
}

insert_ko() {
	insmod $PATH_MODULE/mhal.ko
	insmod $PATH_MODULE/mi_common.ko
	insmod $PATH_MODULE/mi_sys.ko cmdQBufSize=768 logBufSize=256
	insmod $PATH_MODULE/mi_rgn.ko
	insmod $PATH_MODULE/mi_ldc.ko
	insmod $PATH_MODULE/mi_ai.ko
	insmod $PATH_MODULE/mi_ao.ko
	insmod $PATH_MODULE/mi_mipitx.ko
	insmod $PATH_MODULE/mi_sensor.ko
	insmod $PATH_MODULE/mi_shadow.ko
	insmod $PATH_MODULE/mi_divp.ko
	insmod $PATH_MODULE/mi_vif.ko
	insmod $PATH_MODULE/mi_vpe.ko
	insmod $PATH_MODULE/mi_venc.ko fw_path=/etc/firmware/chagall.bin

	MAJOR=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
	mknod /dev/mi_poll c "$MAJOR" 0
	echo isproot /etc/firmware > /dev/ispmid
}

if [ ! -e /sys/module/mhal ]; then
	insert_ko
fi

echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
detect_sensor

if [ -z "$SENSOR" ]; then
	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
	exit 1
else
	echo -e "\n\e[1;32mSensor assigned - $SENSOR\e[0m\n" | logger -s -t OpenIPC
	SENSOR_MODULE=$(ls /sys/module | grep $SENSOR)
	if [ -n "$SENSOR_MODULE" ]; then
		rmmod $SENSOR_MODULE
	fi
	set_sensor
fi

exit 0
