#!/bin/sh

kernel_ver=$(uname -r)
cd /lib/modules/$kernel_ver/goke

USE_OLD_SENSOR_DRIVER=NO    #YES or NO, default no use.
USE_LOAD_HAL_DRIVER=YES      #YES or NO, default no use.

if [ $USE_LOAD_HAL_DRIVER = "YES" ];then
    insmod hal.ko
fi

insmod hw_crypto.ko
insmod media.ko
insmod audio.ko

if [ $USE_OLD_SENSOR_DRIVER = "YES" ]; then
    if [ -e ${1}.ko ];then
        insmod ${1}.ko 
    else
        echo "${1}.ko is no exist."
        exit 0
    fi
else
    insmod sensor.ko

    sensordetect

    if [ -e /tmp/sensor_ex.ko ]; then
        insmod /tmp/sensor_ex.ko 
    fi
fi
