#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

if [ "$1" = "atbm603x-ssc335-tapo-c110" ]; then
	set_gpio 16 1
        modprobe atbm603x_wifi_usb
        exit 0
fi

exit 1
