#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# T23 JOOAN A6M-U
if [ "$1" = "atbm601x-t23-jooan-a6m-u" ]; then
	set_gpio 6 1
	modprobe atbm6012b_wifi_usb
	exit 0
fi

exit 1
