#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# T23 LSC 3215672
if [ "$1" = "atbm601x-t23-lsc-3215672" ]; then
	set_gpio 62 0
	modprobe atbm6012b_wifi_usb
	exit 0
fi

exit 1
