#!/bin/sh

case "$1" in
    start)
        # Disable IR led
        devmem 0x112c0074 32 0
        gpio clear 52
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac
