#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# GK7202V300 XG521 with EC800E and usb0
if [ "$1" = "ec800e-gk7202v300-xg521" ]; then
        set_gpio 9 0
        modprobe usbserial vendor=0x2c7c product=0x0903
        modprobe rndis_host
        sleep 10
        exit 0
fi

exit 1
